[build]
  base = "packages/app"
  command = "npm run build:app"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_MEDPLUM_SERVER_URL = "https://api.medplum.com/"
  # Add the following lines if you have these variables set in your Netlify UI
  # VITE_MEDPLUM_CLIENT_ID = "your-client-id"
  # VITE_MEDPLUM_PROJECT_ID = "your-project-id"